### ISSUE TITLE
Where to put the locale setting?

### ISSUE THREAD

**Issue by Ba55ie** [requirejs/i18n#23]
According to [the documentation](http://requirejs.org/docs/api.html#i18n) the locale setting should be a property of the i18n object, but I also got it to work as a direct property of the config object. So my question is, what is the preferred way for setting the locale?

```javascript
// This works
require.config({
  locale: 'en-gb'
});

// and this is the documented way
require.config({
  config: {
    i18n: {
      locale: 'en-gb'
    }
  }
});
```
Versions used: RequireJS 2.1.15 and i18n 2.0.4

**Comment by crebuh** [comment]
I also have the same issue 

+1

**Comment by jrburke** [comment]
Sorry for the confusion, the direct config assignment was a legacy thing, still supported in the i18n.js plugin for backwards compatibility. 

Setting it via module config, the second example, and now as shown in the http://requirejs.org/docs/api.html#i18n docs section is the way to do it going forward. If there is a docs section that shows the old approach, feel free to let me know and I will correct it.

Going to close this ticket with that answer, but if there are doc changes I need to do comment and I can reopen.

**Comment by ba55ie** [comment]
OK, thanks for the clarification.
