### ISSUE TITLE
Bower package

### ISSUE THREAD

**Issue by pilou** [requirejs/i18n#33]
I see the the bower.js, but cant find the package here http://bower.io/search.

I think its because the package is not made yet.

Could you please create the package, and also create an `Install` section to the docs?

**Comment by tabone** [comment]
I believe its [this](http://bower.io/search/?q=requirejs-i18n).

**Comment by tabone** [comment]
I think you need to search for [requirejs-i18n](http://bower.io/search/?q=requirejs-i18n)
