### ISSUE TITLE
Possible to pull translations with ajax?

### ISSUE THREAD

**Issue by nine-2-five** [requirejs/i18n#35]
I have a backbone app that connects to a wordpress app and would need to get the translations from the wordpress by ajax if possible?

**Comment by jrburke** [comment]
I am not familiar enough with the specifics of wordpress to provide help.

Closing as a discussion ticket, but feel free to continue discussion here.

**Comment by nine-2-five** [comment]
Sorry, my main question is whether it's possible to get labels.js from a remote source through ajax?
