### ISSUE TITLE
Leveraging the if document.documentElement.lang for the locale choice

### ISSUE THREAD

**Issue by masterbee** [requirejs/i18n#37]
@jrburke et al. any thoughts on leveraging the document.documentElement.lang as part of the fallbacks if there is no local set?

I can understand leveraging the navigation property but for sites that offer content in different languages, this gets a bit challenging if users go on languages that are not there browser settings. 

I am more talking about the cases (which in some of my experiences is often) where people come to sites on computers in libraries and so forth where they may not have control to change there local to the language of there choice.

Thoughts?

I am work on a quick P.R. if you think this has value.

**Comment by jrburke** [comment]
If you want to explicitly set the locale, you can [set the value via requirejs.config()](http://requirejs.org/docs/api.html#i18n):

``` javascript
requirejs.config({
    config: {
        i18n: {
            locale: 'fr-fr'
        }
    }
});
```

If you wanted to use `document.documentElement.lang` for the value in that config, that is an option too, just not sure if the value needs to be normalized to the locale format expected by i18n.js.

So given that, I don't feel the need to add more to the code for this. It starts to get tricky in that case to decide what takes priority, and by explicitly setting it via the config, it is a very clear statement.
